### ISSUE TITLE
网页的时间显示似乎有问题

### ISSUE THREAD

**Issue by GitPinkRabbit** [piterator-org/luogu-discussion-archive#10]
![image](https://github.com/piterator-org/luogu-discussion-archive/assets/46786295/daca171a-8a75-4996-912b-76a8b402655a)

![image](https://github.com/piterator-org/luogu-discussion-archive/assets/46786295/2a0cffc9-8f91-4e44-ac15-30ed7bac03f3)

不排除是我开了 VPN 的情况，但是我关掉并退出 VPN、重启浏览器之后，仍然如上偏差 8 小时

**Comment by wxh06** [comment]
对的，已知问题。服务器用的 UTC 时区，稍后修复。

**Comment by GitPinkRabbit** [comment]
好像还没修复啊

**Comment by GitPinkRabbit** [comment]
好像还没修复啊

**Comment by wxh06** [comment]
好像还没修复啊

**Comment by wxh06** [comment]
在服务器上设置了环境变量 `TZ="Asia/Shanghai"`。
Node.js 在第一次读取 `process.env.TZ` 之后再修改时区不会再生效，因此 5db5e249cf3644bd5a05589ff76b67a0cba6f791 并没有修复问题。
