### ISSUE TITLE
新帖子无法被保存

### ISSUE THREAD

**Issue by GitPinkRabbit** [piterator-org/luogu-discussion-archive#14]
![image](https://github.com/piterator-org/luogu-discussion-archive/assets/46786295/3a137dc1-de18-45d6-b1cf-134a373abb3b)

复现：访问 <https://lglg.top/745659>

**Comment by GitPinkRabbit** [comment]
疑似掉登录了，置顶帖也只能保存第一页

**Comment by wxh06** [comment]
> 疑似掉登录了

看起来是的。
实际上修 #10 的时候发现登录过期，是更新过 cookie 的，但是未知原因没有生效。

**Comment by wxh06** [comment]
> 更新过 cookie 的，但是未知原因没有生效。

应该是 @YuzhenQin 的服务器未知原因重启（`pm2 list` 可以看见服务持续运行 11h，重启 0 次），但更新后的环境变量没有持久化保存，现在 `pm2 save` 过了应该没问题了。

**Comment by YuzhenQin** [comment]
> > 更新过 cookie 的，但是未知原因没有生效。
> 
> 应该是 @YuzhenQin 的服务器未知原因重启（`pm2 list` 可以看见服务持续运行 11h，重启 0 次），但更新后的环境变量没有持久化保存，现在 `pm2 save` 过了应该没问题了。

应该是 Vultr 维护。Vultr 天天维护。

**Comment by GitPinkRabbit** [comment]
cookie 又过期了？
