### ISSUE TITLE
UserSnapshot 去重问题

### ISSUE THREAD

**Issue by YuzhenQin** [piterator-org/luogu-discussion-archive#15]
有去重代码，但是还是会重复。

https://github.com/piterator-org/luogu-discussion-archive/blob/5db5e249cf3644bd5a05589ff76b67a0cba6f791/packages/archive/src/lib/user.ts#L23

```typescript
if (
      lastSnapshot !== null &&
      user.ccfLevel === lastSnapshot.ccfLevel &&
      user.badge === lastSnapshot.badge &&
      user.isAdmin === lastSnapshot.isAdmin &&
      user.isBanned === lastSnapshot.isBanned &&
      (user.isRoot ?? null) === lastSnapshot.isRoot &&
      user.color === lastSnapshot.color &&
      user.name === lastSnapshot.name
    )
```

**Comment by YuzhenQin** [comment]
@wxh06 @immccn123

**Comment by immccn123** [comment]
这个东西我负全责 按理说会在有个地方有个 `return` 但是似乎忘记写了

fixed in https://github.com/piterator-org/luogu-discussion-archive/commit/a7a47e802bd671e024610717eddd7fedae66ed21
