### ISSUE TITLE
cookie 又过期了？

### ISSUE THREAD

**Issue by GitPinkRabbit** [piterator-org/luogu-discussion-archive#16]

**Comment by GitPinkRabbit** [comment]
@wxh06 @eventlOwOp @ForkKILLET @immccn123

**Comment by eventlOwOp** [comment]
服务器到期了，貌似wbh没备份，所以现在用不了

**Comment by eventlOwOp** [comment]
我们的 @wxh06 老师备份了，快感谢他

**Comment by wxh06** [comment]
> 我们的 @wxh06 老师备份了，快感谢他

我操了，11GB 的数据库，我现在硬盘满了装不了双人成行我女朋友要急了 🤡
