### ISSUE TITLE
[BUG] 服务器时间问题

### ISSUE THREAD

**Issue by 318cyz** [piterator-org/luogu-discussion-archive#18]
rt，服务器时间是 UTC 而非北京时间，所有网页上显示的时间都比实际时间早 8 个小时。

**Comment by wxh06** [comment]
Duplicate of #10

**Comment by wxh06** [comment]
@smallfangqwq pm2 里给 viewer 加个环境变量 `TZ="Asia/Shanghai"`。

**Comment by smallfangqwq** [comment]
> @smallfangqwq pm2 里给 viewer 加个环境变量 `TZ="Asia/Shanghai"`。

it doesn't works
