### ISSUE TITLE
洛谷国际站问题

### ISSUE THREAD

**Issue by LuohanXiao** [piterator-org/luogu-discussion-archive#20]
最近，洛谷国际化，一些老帖子转移到了 <luogu.com>

可经过测试，洛谷帖子保存站无法保存、更新 <luogu.com> 上的帖子，并会报错`Unexpected token < in JSON at position 0`

**Comment by wxh06** [comment]
与 #19 有关。

**Comment by wxh06** [comment]
`Unexpected token < in JSON at position 0` 明显是尝试解析 JSON，但洛谷以 HTML 的格式返回了页面。

**Comment by wxh06** [comment]
> 可经过测试，洛谷帖子保存站无法保存、更新 <luogu.com> 上的帖子

您是否指的是：在保存站中尝试保存在 luogu.com.cn 被屏蔽、只有在 luogu.com 才展示的（老）帖子，会得到报错

**Comment by LuohanXiao** [comment]
> `Unexpected token < in JSON at position 0`明显是尝试解析 JSON，但洛谷以 HTML 的格式返回了页面。

我猜 HTML 应该是这个：
![屏幕截图_10-6-2024_193444_www luogu com cn](https://github.com/piterator-org/luogu-discussion-archive/assets/165447195/9234071a-7d00-47dc-aef0-dadb7bbfdf13)

**Comment by LuohanXiao** [comment]
> > 可经过测试，洛谷帖子保存站无法保存、更新 <luogu.com> 上的帖子
> 
> 您是否指的是：在保存站中尝试保存在 luogu.com.cn 被屏蔽、只有在 luogu.com 才展示的（老）帖子，会得到报错
是的
