### ISSUE TITLE
新版讨论区无法爬取

### ISSUE THREAD

**Issue by 2043356647** [piterator-org/luogu-discussion-archive#30]
在luogu更新讨论区后，帖子保存站无法爬取帖子，在保存站中最新的帖子还是2024/11/14 02:20的

**Comment by smallfangqwq** [comment]
prs welcome.

**Comment by 2043356647** [comment]
原因是在luogu讨论区更新后，列出帖子和获取帖子的相应主体由`DataResponse` 变为`LentilleDataRespons`，无法再使用`_contentOnly`参数，需要头字段`x-lentille-request`（值为`content-only`）来获取

**Comment by 2043356647** [comment]
不太会改代码，希望有大佬可以改一下api

**Comment by immccn123** [comment]
已修复并部署
