### ISSUE TITLE
已在爱发电打赏 30 RMB~ 请问能否恢复保存站运行？能否持续运行一段时间？

### ISSUE THREAD

**Issue by GitPinkRabbit** [piterator-org/luogu-discussion-archive#6]
https://afdian.net/a/piterator?tab=sponsor

**Comment by wxh06** [comment]
非常抱歉，我们的香港云服务器提供商又双叒叕寄了（至今无法进行重启操作。。。），现在已经切换到备用的日本线路。

**Comment by wxh06** [comment]
非常抱歉，除反代服务器外，我才发现在 10 月底的时候用于数据库的服务器磁盘就满了。刚刚清除了一些 `node_modules`，现已经恢复正常。

**Comment by GitPinkRabbit** [comment]
感谢维护。又打赏了 20 RMB / 月 × 5 月

**Comment by GitPinkRabbit** [comment]
![image](https://github.com/piterator-org/luogu-discussion-archive/assets/46786295/8ceb7e18-1326-451c-8b83-405bbf6ccf49)

想问问为什么这么不稳定 🙁 以及龙王榜好像加载得很慢

**Comment by GitPinkRabbit** [comment]
访问 https://lglg.top/explore 时最终出现报错

```plain
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3026084215
```

是什么情况呢？

**Comment by wxh06** [comment]
> 想问问为什么这么不稳定

腾讯云的服务器经常出现突然性没有任何响应，SSH 不能的情况 :(

> 出现报错 `Application error: a server-side exception has occurred (see the server logs for more information).` 是什么情况呢？

出现“服务器端异常”一般是由于数据库连接池满了，导致 SQL 查询超时：

```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)
```

**Comment by wxh06** [comment]
> 腾讯云的服务器经常出现突然性没有任何响应，SSH 不能的情况 :(

经初步排查，可能存在内存泄漏。正在尝试在开发环境中复现。

**Comment by wxh06** [comment]
> 经初步排查，可能存在内存泄漏。

用 pm2 给进程上了个[内存限制](https://pm2.keymetrics.io/docs/usage/memory-limit/)，现在应该不会频繁挂掉了；但是 SQL 查询过慢的问题暂时没有解决。

**Comment by wxh06** [comment]
> 用 pm2 给进程上了个[内存限制](https://pm2.keymetrics.io/docs/usage/memory-limit/)，现在应该不会频繁挂掉了

啪！脸好疼！这次用时不到 10 分钟。

**Comment by GitPinkRabbit** [comment]
几个月以前用着挺流畅的啊，怎么现在几乎上不了

**Comment by wxh06** [comment]
给进程加了 1GB 内存限制后，服务器状态趋于稳定；
在 9a78aa373dd12f88e078fc068805f9aa02ec16bb 中给一些数据库字段加了索引，发现页面加载缓慢的问题仍然没有得到解决。

**Comment by GitPinkRabbit** [comment]
> 几个月以前用着挺流畅的啊，怎么现在几乎上不了

所以是为什么呢？几个月以前和现在的版本区别在于哪里？

**Comment by GitPinkRabbit** [comment]
访问 https://lglg.top/727182 的时候服务器返回 500？

**Comment by immccn123** [comment]
> 访问 https://lglg.top/727182 的时候服务器返回 500？

上游库有一堆锅导致的 情况比较复杂 尝试但降级不起作用

上游新版本存在内存泄漏 降到旧版本然后又是这个阴间错误 只能先等上游修了 抱歉

<https://stackoverflow.com/questions/77138105/reactmarkdown-remarkgfm-everything-renders-as-expected-except-tables-typee>

依赖的 `remark-gfm` 导致这个错误 升级 `react-markdown` 可以解决 但是 `rehype-highlight` 新版本存在内存泄漏 旧版本不与 `react-markdown` 新版本兼容 所以就卡在这里了

**Comment by immccn123** [comment]
> > 几个月以前用着挺流畅的啊，怎么现在几乎上不了
> 
> 所以是为什么呢？几个月以前和现在的版本区别在于哪里？

现在的版本基本上对于所有东西全部「打快照」而不是覆写 目前来看的话 逻辑的变动导致数据库 io 非常高 导致响应速度降低 修改基本的 schema 现在不现实 增加性能的方法有待商讨 非常抱歉带来不好的体验

**Comment by GitPinkRabbit** [comment]
我主要就是想访问 <https://lglg.top/explore>，能否提升这个页面的稳定性？
