### ISSUE TITLE
能否优先提升“发现”页面的稳定性？

### ISSUE THREAD

**Issue by GitPinkRabbit** [piterator-org/luogu-discussion-archive#9]
见 https://github.com/piterator-org/luogu-discussion-archive/issues/6#issuecomment-1807708226

（我是打赏了 130 RMB 的金主，能不能看看我的需求）

**Comment by GitPinkRabbit** [comment]
救一下啊

**Comment by wxh06** [comment]
查询效率的问题暂时没有办法解决，目前唯一可行的方案是换服务器。
@YuzhenQin 方便的话晚点租一台 Vultr 的机子，我有空的时候迁移过去。
我们腾讯云上海的机子水管比较细，数据库搬过去要花点时间的。

> 我是打赏了 130 RMB 的金主，能不能看看我的需求

钱全进 @bohanjun 口袋里啦，快打倒带资本家，我们打工人一分钱都拿不到（x
（虽然本来就是用爱发电，其实无所谓的）

**Comment by GitPinkRabbit** [comment]
@bohanjun 你独吞？？

**Comment by YuzhenQin** [comment]
> 见 [#6 (comment)](https://github.com/piterator-org/luogu-discussion-archive/issues/6#issuecomment-1807708226)
> 
> （我是打赏了 130 RMB 的金主，能不能看看我的需求）

我们目前已经租用了一台 Vultr 的机器（独立核心），即将进行迁移。

（$30 一个月，好贵啊

**Comment by wxh06** [comment]
> $40 一个月，好贵啊

$40 一个月？这么贵？
我考虑一下家里云的可行性。按理来说家里的机子重启到 Arch Linux 拿来当服务器没什么大问题，但是那样我就不能启 Windows 陪我女朋友打游戏了。

**Comment by wxh06** [comment]
Vultr 环境配好了，稍后将会暂停保存并迁移数据库。

**Comment by wxh06** [comment]
服务器配好了，但是 TSL 证书没下来，暂时访问不了。发现页面现在可以在 40s 内加载完成 😅

**Comment by wxh06** [comment]
能用了。性能问题没有完全解决，但通过增加配置的方式得到了改善。

**Comment by YuzhenQin** [comment]
观察到打开发现页面时 CPU 占用率迅速提高到 100% 并保持较长时间

**Comment by YuzhenQin** [comment]
之前实际上没有打索引。

现在“发现”页面能在 15s 内加载出帖子内容，得到了一定改善。

但是现在发现 `("userId", "time" DESC)` 的索引无法被使用。

**Comment by GitPinkRabbit** [comment]
只能说现在终于恢复到可以用的水平了

**Comment by YuzhenQin** [comment]
> 只能说现在终于恢复到可以用的水平了

只能说换了 $80 一个月（4 个独立的 EPYC 核心，8GB 内存）之后，发现页面还要 5s。

我只能说 @bohanjun 的设计太逆天了，尤其是 `UserSnapshot` 这里。

**Comment by YuzhenQin** [comment]
fixed in https://github.com/piterator-org/luogu-discussion-archive/commit/a7a47e802bd671e024610717eddd7fedae66ed21
